db.categories.insert([
    {parent: 'Латексные шары', child: 'Без рисунка'},
    {parent: 'Латексные шары', child: 'С рисунком'},
    {parent: 'Латексные шары', child: 'Для моделирования'},
    {parent: 'Латексные шары', child: 'Фигурные'},
    {parent: 'Латексные шары', child: 'Сердца'},
    {parent: 'Фольгированные шары', child: 'Без рисунка'},
    {parent: 'Фольгированные шары', child: 'С рисунком'},
    {parent: 'Фольгированные шары', child: 'Цифры'},
    {parent: 'Фольгированные шары', child: 'Мини фигуры'},
    {parent: 'Фольгированные шары', child: 'Большие фигуры'},
    {parent: 'Фольгированные шары', child: 'Ходячие фигуры'},
    {parent: 'Аксессуары для шаров', child: 'Палочки-держатели'},
    {parent: 'Аксессуары для шаров', child: 'Лента/Тесьма для шаров'},
    {parent: 'Аксессуары для шаров', child: 'Компрессоры/Ручные насосы'},
    {parent: 'Аксессуары для шаров', child: 'Жидкость для шаров'},
    {parent: 'Всё для праздника', child: 'Свечи для торта'},
    {parent: 'Всё для праздника', child: 'Конфетти/Мишура'},
    {parent: 'Всё для праздника', child: 'Шторы-занавес из фольги'},
    {parent: 'Всё для праздника', child: 'Небесные фонарики'},
    {parent: 'Всё для праздника', child: 'Хлопушки'},
    {parent: 'Всё для праздника', child: 'Гирлянды-растяжки'},
    {parent: 'Всё для праздника', child: 'Праздничная бутафория'},
    {parent: 'Всё для праздника', child: 'Сувенирные деньги'},
    {parent: 'Всё для праздника', child: 'Конверты для денег'},
    {parent: 'Всё для праздника', child: 'Наклейки'},
    {parent: 'Всё для праздника', child: 'Колпаки/Тарелки/Стаканы'},
    {parent: 'Всё для праздника', child: 'Упаковочная бумага'},
    {parent: 'Календари', child: 'Плакаты'},
    {parent: 'Календари', child: 'Третинка'},
    {parent: 'Календари', child: 'А4 скоба'},
    {parent: 'Календари', child: 'Мини-квадрат'},
    {parent: 'Календари', child: 'Горизонтальный'},
    {parent: 'Календари', child: 'Горка'},
    {parent: 'Календари', child: '3 пружины с бегунком'},
    {parent: 'Календари', child: '1 пружина с бегунком'},
    {parent: 'Календари', child: 'Календари на 10 лет'},
    {parent: 'Календари', child: 'Календари на магните'},
    
])

db.products.insert([
    {
        title: 'Зверюшки-игрушки 30см',
        description: 'Шар бла бла бла1',
        code: 1343,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '211.38 грн',
        pieces: '50 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'ДР Суперстар 30см',
        description: 'Шар бла бла бла2',
        code: 1340,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '121.81 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'ДР Слонёнок',
        description: 'Шар бла бла бла3',
        code: 1294,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '121.81 грн',
        pieces: '50 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Узор Барокко 30см',
        description: 'Шар бла бла бла4',
        code: 1264,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '150.02 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Морская 30см',
        description: 'Шар бла бла бла5',
        code: 1257,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '162.32 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Листья тропические 30см',
        description: 'Шар бла бла бла6',
        code: 1265,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '139.51 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Космос 30см',
        description: 'Шар бла бла бла7',
        code: 1285,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '121.81 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Для мамы 30см',
        description: 'Шар бла бла бла8',
        code: 1279,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '183.92 грн',
        pieces: '50 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Самый лучший день 30см',
        description: 'Шар бла бла бла9',
        code: 1272,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '183.92 грн',
        pieces: '50 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'ДР Торт со свечами 30см',
        description: 'Шар бла бла бла10',
        code: 1271,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '121.81 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'С ДР сыночка 30см',
        description: 'Шар бла бла бла11',
        code: 1267,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '121.81 грн',
        pieces: '25 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    },
    {
        title: 'Собачки 30см',
        description: 'Шар бла бла бла12',
        code: 1342,
        category: 'Латексные шары',
        subCategory: 'С рисунком',
        price: '211.38 грн',
        pieces: '50 шт',
        sizeCm: 12 ,
        color: 'Ассорти',
        maker: 'Belbal' ,
        type: 'Пастель',
        soldOut: false
    }
])


